spring:
    application:
        name: SpringBatchReaderWriter
    datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: your_username
    password: your_password
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true